fix: simplify firmware path check and quote sysfs path
Signed-off-by: andrewwhitecdw <andrewwhitecdw@users.noreply.github.com>

diff --git a/rhel8/nvidia-driver b/rhel8/nvidia-driver
--- a/rhel8/nvidia-driver
+++ b/rhel8/nvidia-driver
@@ -388,11 +388,11 @@ _load_driver() {
 
     if [[ "$set_fw_path" == "true" ]]; then
         echo "Configuring the following firmware search path in '$fw_path_config_file': $nv_fw_search_path"
-        if [[ ! -z $(grep '[^[:space:]]' $fw_path_config_file) ]]; then
+        if grep -q '[^[:space:]]' "$fw_path_config_file"; then
             echo "WARNING: A search path is already configured in $fw_path_config_file"
             echo "         Retaining the current configuration"
         else
-            echo -n "$nv_fw_search_path" > $fw_path_config_file || echo "WARNING: Failed to configure the firmware search path"
+            echo -n "$nv_fw_search_path" > "$fw_path_config_file" || echo "WARNING: Failed to configure the firmware search path"
         fi
     fi
 
